### ISSUE TITLE
Can't create a site on Tableau server 8.2

### ISSUE THREAD

**Issue by tchyzh** [TraxTechnologies/tableau-ruby#1]
When I'm trying to execute this part: @site = @client.sites.create(name: "abcdasds")
it returns me an error "{\"error\":409}"
After reading the error conditions here's what the documentation says.

409 	Site name conflict 	The site name in the request already belongs to an existing site in the system.
409 	Site URL conflict 	The content URL in the request already belongs to an existing site in the system.
409 	Admin mode/user quota conflict 	The request cannot set adminMode to ContentOnly and specify a userQuota.

There's no site name "abcdasds" in my system. Can you please help me with what I'm doing wrong???

**Comment by kcollignon** [comment]
Hi @tchyzh ,
Would you mind posting an example of your Tableau client initialization code? Thanks!
